[pins]
[pins.1]
[pins.1.A]
0 = 'OUT'
1 = 'IN'
2 = 'IN'
3 = 'IN'
4 = 'IN'
5 = 'IN'
6 = 'IN'
7 = 'IN'
[pins.1.B]
0 = 'IN'
1 = 'IN'
2 = 'IN'
3 = 'IN'
4 = 'IN'
5 = 'IN'
6 = 'IN'
7 = 'IN'
[pins.2]
[pins.2.A]
0 = 'IN'
1 = 'IN'
2 = 'IN'
3 = 'IN'
4 = 'IN'
5 = 'IN'
6 = 'IN'
7 = 'IN'
[pins.2.B]
0 = 'IN'
1 = 'IN'
2 = 'IN'
3 = 'IN'
4 = 'IN'
5 = 'IN'
6 = 'IN'
7 = 'IN'
[pins.3]
[pins.3.A]
0 = 'IN'
1 = 'IN'
2 = 'IN'
3 = 'IN'
4 = 'IN'
5 = 'IN'
6 = 'IN'
7 = 'IN'
[pins.3.B]
0 = 'IN'
1 = 'IN'
2 = 'IN'
3 = 'IN'
4 = 'IN'
5 = 'IN'
6 = 'IN'
7 = 'IN'
[pins.4]
[pins.4.A]
0 = 'IN'
1 = 'IN'
2 = 'IN'
3 = 'IN'
4 = 'IN'
5 = 'IN'
6 = 'IN'
7 = 'IN'
[pins.4.B]
0 = 'IN'
1 = 'IN'
2 = 'IN'
3 = 'IN'
4 = 'IN'
5 = 'IN'
6 = 'IN'
7 = 'IN'
[pins.5]
[pins.5.A]
0 = 'IN'
1 = 'IN'
2 = 'IN'
3 = 'IN'
4 = 'IN'
5 = 'IN'
6 = 'IN'
7 = 'IN'
[pins.5.B]
0 = 'IN'
1 = 'IN'
2 = 'IN'
3 = 'IN'
4 = 'IN'
5 = 'IN'
6 = 'IN'
7 = 'IN'
[pins.6]
[pins.6.A]
0 = 'IN'
1 = 'IN'
2 = 'IN'
3 = 'IN'
4 = 'IN'
5 = 'IN'
6 = 'IN'
7 = 'IN'
[pins.6.B]
0 = 'IN'
1 = 'IN'
2 = 'IN'
3 = 'IN'
4 = 'IN'
5 = 'IN'
6 = 'IN'
7 = 'IN'
[pins.7]
[pins.7.A]
0 = 'IN'
1 = 'IN'
2 = 'IN'
3 = 'IN'
4 = 'IN'
5 = 'IN'
6 = 'IN'
7 = 'IN'
[pins.7.B]
0 = 'IN'
1 = 'IN'
2 = 'IN'
3 = 'IN'
4 = 'IN'
5 = 'IN'
6 = 'IN'
7 = 'IN'
[pins.8]
[pins.8.A]
0 = 'IN'
1 = 'IN'
2 = 'IN'
3 = 'IN'
4 = 'IN'
5 = 'IN'
6 = 'IN'
7 = 'IN'
[pins.8.B]
0 = 'IN'
1 = 'IN'
2 = 'IN'
3 = 'IN'
4 = 'IN'
5 = 'IN'
6 = 'IN'
7 = 'IN'
